Update to version 0.8.0
flathub/com.beakerbrowser.Beaker pull request #1
Opened 2018-10-22 18:47 UTC by da2x

This version was released an hour ago.
https://github.com/beakerbrowser/beaker/releases/tag/0.8.0

I believe this is all that’s required, but should undergo more testing.

2018-10-22 20:51 UTC, G-Ray commented
Thank you @da2x 

You also need to update "com.beakerbrowser.Beaker.appdata.xml", can you ?

Have you tested the build locally following ? You can refer to http://docs.flatpak.org/en/latest/electron.html#building-the-sample-application

2018-10-22 20:52 UTC, G-Ray requested changes
Please update `com.beakerbrowser.Beaker.appdata.xml`

2018-10-22 22:11 UTC, da2x commented
> Have you tested the build locally following […]

Yes, and it appears to work.

> Please update com.beakerbrowser.Beaker.appdata.xml

I missed that. Thanks, it’s done now.

2018-10-23 09:18 UTC, G-Ray approved these changes

2018-10-23 09:18 UTC, merged

2018-10-23 09:18 UTC, G-Ray commented
Thank you :heart: